version: '3.8'

services:
  # FastAPI REST API
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/smart_retail
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-here
      - ENVIRONMENT=development
    depends_on:
      - postgres
      - redis
    volumes:
      - ./api:/app
    restart: unless-stopped
    networks:
      - smart-retail-network

  # MCP Server (existing)
  mcp-server:
    build:
      context: ./mcp
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/smart_retail
      - MONGODB_URL=mongodb://mongo:27017/retail_analytics
    depends_on:
      - postgres
      - mongo
    restart: unless-stopped
    networks:
      - smart-retail-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=smart_retail
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped
    networks:
      - smart-retail-network

  # MongoDB for Analytics
  mongo:
    image: mongo:7-jammy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - smart-retail-network

  # Redis for Caching and Background Jobs
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - smart-retail-network

  # Celery Worker for Background Tasks
  celery-worker:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: celery -A main.celery worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/smart_retail
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - postgres
      - redis
    volumes:
      - ./api:/app
    restart: unless-stopped
    networks:
      - smart-retail-network

  # Celery Beat for Scheduled Tasks
  celery-beat:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: celery -A main.celery beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/smart_retail
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - postgres
      - redis
    volumes:
      - ./api:/app
    restart: unless-stopped
    networks:
      - smart-retail-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - mcp-server
    restart: unless-stopped
    networks:
      - smart-retail-network

volumes:
  postgres_data:
  mongo_data:
  redis_data:

networks:
  smart-retail-network:
    driver: bridge 